### ISSUE TITLE
Crash on Forge version 47.2.20

### ISSUE THREAD

**Issue by Nelly1234567** [dragon-forge/HammerMultipart#1]
Good day, 

The mods 'HammerMultipart' and 'HammerMicroblocks' seem to not be able to register some of the newer version of forge. I'm working on a modpack that's using Forge version 47.2.20 and upon starting the pack, these two mods present a message of "<ModName> needs language provider javafml:47.1 or above to load. We have found 47"

Here's a link to the crash report:
https://pastebin.com/D7ei1m60

Hopefully it is a simple fix.
Thanks!

**Comment by Zeitheron** [comment]
Use NeoForge.
